// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkMxO6puUkYbSz0JAFTRitfSlPi3pZG4',
    appId: '1:447911728427:web:76bdc8dec5e65d82a0216e',
    messagingSenderId: '447911728427',
    projectId: 'flutter-instagram-clone-2c8f5',
    authDomain: 'flutter-instagram-clone-2c8f5.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-2c8f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw1x9z2EpJHSuYUsNazTDt_nD9vLuI5Cs',
    appId: '1:447911728427:android:0ce23aa4b3f09fc3a0216e',
    messagingSenderId: '447911728427',
    projectId: 'flutter-instagram-clone-2c8f5',
    storageBucket: 'flutter-instagram-clone-2c8f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0IwTE6yTai8IfJYlHbcwY-qoggVD3-4Y',
    appId: '1:447911728427:ios:e6f2a34d66919148a0216e',
    messagingSenderId: '447911728427',
    projectId: 'flutter-instagram-clone-2c8f5',
    storageBucket: 'flutter-instagram-clone-2c8f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0IwTE6yTai8IfJYlHbcwY-qoggVD3-4Y',
    appId: '1:447911728427:ios:e6f2a34d66919148a0216e',
    messagingSenderId: '447911728427',
    projectId: 'flutter-instagram-clone-2c8f5',
    storageBucket: 'flutter-instagram-clone-2c8f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}